【WIP】バックエンド試験 雛形作成
EeeeG-Inc/Backend-Coding-Test-01 pull request #1
Opened 2022-06-16 09:49 UTC by katakabe

2022-06-16 10:00 UTC, Takuma-Ikeda requested changes
さくっとレビューしました！引き続きお願いします！

2022-06-16 10:00 UTC, iQeda commented on .gitignore
> +.git/
下記も追加してほしいです！
- https://github.com/github/gitignore/blob/2178fe898497d982a2c98242bdb95df3d561bf70/Global/VisualStudioCode.gitignore
- https://github.com/github/gitignore/blob/main/Global/macOS.gitignore
- https://github.com/github/gitignore/blob/7ad34f7adba8546a19e3245e163e5502c338490a/Node.gitignore

2022-06-16 10:00 UTC, iQeda commented on detail.html
> +  <style>
style は CSS  ファイルに書いてほしいです！

2022-06-16 10:00 UTC, iQeda commented on detail.html
> +  <title>2022 Calendar</title>
ここもプログラムの対象かと思ってしまうので西暦は不要かと！
※ 西暦書いてしまうと毎年メンテしなくちゃいけなくなる...

2022-06-16 10:00 UTC, Takuma-Ikeda commented on detail.html
> +          <input type="button" value="変更">&nbsp;&nbsp;<input type="button" value="削除">
あんまり半角スペースでデザイン作ってほしくないです
CSS でマージン・パディング使いましょう

2022-06-16 10:05 UTC, Takuma-Ikeda requested changes

2022-06-16 10:05 UTC, Takuma-Ikeda commented on detail.html
> +          <label for="scheduleNameInput">予定名</label>
for に対応する id が抜けてますね

2022-06-16 10:11 UTC, Takuma-Ikeda commented on detail.html
> +          <input type="button" value="変更">&nbsp;&nbsp;<input type="button" value="削除">
value は「変更」じゃなくて「編集」がいいです！

2022-06-16 10:18 UTC, Takuma-Ikeda requested changes

2022-06-16 10:18 UTC, Takuma-Ikeda commented on detail.html
> +          <textarea class="form-control" rows="3"></textarea>
https://web-camp.io/magazine/archives/89515
row じゃなくて CSS で制御してほしいです！
※ row や col だと意図したサイズにするの難しいので
```css
width:100%;
height:100px;
```

2022-06-16 10:18 UTC, iQeda commented on detail.html
> +          <input type="time" class="form-control">〜<input type="time" class="form-control">
HTML タグを改行してほしいです。
prettier 有効にすればいい感じになると思います。

2022-06-16 10:18 UTC, iQeda commented on index.html
> +        <h3 class="mb-5"><a href="#">&lt;</a>&nbsp;2022年 6月&nbsp;<a href="#">&gt;</a></h3>
ここも半角スペース使わないほうがいいですね

2022-06-17 02:32 UTC, Takuma-Ikeda commented
@katakabe 
追加でフッターに `EeeeG, Inc` のコピーライト入れてほしいです！
GitHub に明記するのは MIT ライセンスで大丈夫です！

2022-06-17 07:12 UTC, katakabe commented
@Takuma-Ikeda 
Review 対応ありがとうございました！
Review 反映及び 新規登録 / 編集ページの作成を実施させていただきました。
お手すきの際にご査収の程よろしくお願いたします。

2022-06-17 07:46 UTC, Takuma-Ikeda requested changes
引き続きよろしくお願いします！

2022-06-17 07:46 UTC, Takuma-Ikeda commented on index.html
> +    <h3 class="mb-5">20XX年 X月</h3>
ここはプログラム対象なので、わかりやすく `2022 年 6 月`とかでいいと思います

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-create.html
> +  <title>Calendar create</title>
ここは日本語でもいいような気がします。
細かいですがカレンダーを作成するのではなく、スケジュールを作成するので「スケジュール新規作成」かと

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-create.html
> +          <input type="button" value="作成">
ここは「新規作成」で！

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-detail.html
> +  <title>Calendar</title>
ここも日本語で。カレンダーではなく「スケジュール詳細」ですね。

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-detail.html
> +    <h3 class="mb-5">20XX年X月</h3>
ここもプログラム対象で、ダミー日時のほうがわかりやすいので `2022年6月1日` とかでいいと思います

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-detail.html
> +      <th>予定内容1</th>
モックなので、ダミーっぽい値がいいですね。
タスク名は「A社とミーティング」とか「コーディング試験」とかでどうでしょう

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-edit.html
> +  <title>Calendar edit</title>
ここは「スケジュール編集」などにしましょうか

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-edit.html
> +          <label for="scheduleNameInput">予定名</label>
ここもわかりやすいダミーデータでお願いします

2022-06-17 07:46 UTC, Takuma-Ikeda commented on schedule-edit.html
> +          <input type="button" value="修正">
修正でもよいのですが、よくある言い回しは「保存」とかですかね？

2022-06-17 07:46 UTC, Takuma-Ikeda commented on css/style.css
> +a {
下記を定義して、カレンダーに反映しておいてほしいです！

- 土日・祝日をあらわすスタイル
- 現在日付をあらわすスタイル

2022-06-17 07:52 UTC, Takuma-Ikeda requested changes

2022-06-17 07:52 UTC, Takuma-Ikeda commented on schedule-create.html
> +<!DOCTYPE html>
ファイル名が `schedule-create.html` だと冗長なので、
`schedule` ディレクトリを切って、その配下に `create.html` とかのほうがわかりやすい気がします！

2022-06-17 07:52 UTC, Takuma-Ikeda commented on index.html
> +  Copyright (c) 2022 ©EeeeG, Inc. This software is released under the MIT License, see LICENSE.
2022 の部分は毎年変えないといけないので JavaScript で生成できますか？
面倒なら `(c) EeeeG, Inc.` だけでもいいです！
`(c)` は専用の書き方があるので下記を参照してください！
https://www.rapidtables.com/web/html/html-codes/html-code-copyright.html

2022-06-17 07:57 UTC, Takuma-Ikeda commented on schedule-detail.html
> +      <th>予定内容1</th>
`th` ってヘッダーを表すもので、ここはその値なので `td` タグが適切じゃないでしょうか？

2022-06-17 08:42 UTC, Takuma-Ikeda commented
ここのモックが抜けているので、よろしくお願いします！

> もしスケジュールが存在する場合、カレンダー画面の日付枠内にスケジュールを表示してください
> スケジュールの文字数が多く、日付枠内にスケジュールが収まらない場合は末尾を … (三点リーダー) にしてください
> スケジュール件数が多く、日付枠内にスケジュールが収まらない場合は「他○件」と表示してください

2022-06-17 10:53 UTC, Takuma-Ikeda commented
Slack でもお伝えしましたが GitHub 上で MIT ライセンスが有効になっていないのでこちらよろしくお願いします

2022-06-17 11:24 UTC, Takuma-Ikeda requested changes
コード周り指摘をしました。デザイン周りの指摘は Slack に書いてます！

2022-06-17 11:24 UTC, iQeda commented on index.html
> +          <a href="./schedule/detail.html" class="thisday">
`thisday` じゃなくて `today` がよさそうです

2022-06-17 11:24 UTC, iQeda commented on index.html
> +  <title>Calendar</title>
ここの title だけ英語にするのもなんなので「カレンダー」にしましょうか

2022-06-17 11:24 UTC, iQeda commented on css/style.css
> +
color が同じだったとしても、祝日も定義しておいたほうがよさそうです
※ テストする人がどの class を使うべきかわからなくなるので
holiday でいいかと思います

2022-06-17 11:24 UTC, iQeda commented on css/style.css
> +
平日も定義したほうがいいですね。
weekday でどうでしょうか。

2022-06-17 11:24 UTC, Takuma-Ikeda commented on css/style.css
> +
2022 年の 6 月は祝日がなかったみたいですね。。。
モックとしてわかりやすくするため 7 月にしましょうか！
カレンダーに祝日のデザイン適用をお願いします (海の日など)

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/create.html
> +  (c) EeeeG, Inc.
(C) は記号を使ってください！

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/create.html
> +  <div class="calendar-container">
calendar-container という class は定義していないみたいですよ...

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/create.html
> +    <div class="calender-content">
calender-content もないようです...

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/detail.html
> +  <div id="detailLists">
この id って不要じゃないでしょうか。
この id を使って JavaScript で操作するとか、for と id が対になってるとか、id でスタイリングしている、とかではないと思うので！

仮に id でスタイリングする予定だとしても、div も h3 同じブロック要素なので h3 に直接 id を付けていいですしし、h3 のスタイリングは汎用的であるべきなので id よりも class を使うのがベターとなります。
※ そもそも h3 をスタイリングしたいだけなら div で囲む必要もなさそうです
div がラップしているのは h3 だけなのに id 名が detailLists (複数の詳細リスト) となっているのも、実態と違う気がします！

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/detail.html
> +      <th>タスク</th>
「タスク」よりも「スケジュール名」とか「タイトル」とかが良い気がします
タスクの意味合いは「作業」なので、カレンダーの使い方がそうとも限らないかなと！

また、新規作成・編集画面では「予定名」となっているので統一してほしいです

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/detail.html
> +      <th>タスク</th>
予定詳細を DB 登録しているのに、詳細画面で表示していませんね！

2022-06-17 11:24 UTC, Takuma-Ikeda commented on schedule/detail.html
> +      <th>時刻</th>
ここも「予定日時」なのか「時刻」なのか統一してほしいです！

2022-06-17 11:29 UTC, Takuma-Ikeda commented on schedule/create.html
> +  (c) EeeeG, Inc.
実装ミスがあったにも関わらず GitHub のコメントを Resolove (解決) しちゃってたので注意しましょうか！
※ 指摘コメントが見えなくなると、レビュワー再確認のとき見落としやすくなるとおも
基本的にレビュワーが再確認したときに Resolove 押下するほうがいいかなと思いますね

<img width="1038" alt="スクリーンショット 2022-06-17 20 26 54" src="https://user-images.githubusercontent.com/27577954/174289724-3c5b3877-969d-4b56-860a-17bda198b27e.png">
w

2022-06-17 11:39 UTC, iQeda requested changes

2022-06-17 11:39 UTC, Takuma-Ikeda commented on css/style.css
> +.listInput {
ちょっと細かいですが、`mini-button` のようなケバブケースを使っていたり、
`listInput` のようなキャメルケースを使っていたりで、命名規則に統一感がないですね。

2022-06-17 11:39 UTC, Takuma-Ikeda commented on schedule/edit.html
> +          <input type="text" id="scheduleNameInput" class="form-control" value="A社とミーティング">
ここでも id はキャメルケースなのに、class はケバブケースですね。
Bootstrap の class 名を変えるわけにはいかないのでケバブケースでいいかと思います。

2022-06-19 01:29 UTC, Takuma-Ikeda requested changes

2022-06-19 01:29 UTC, Takuma-Ikeda commented on schedule/create.html
> +          <input type="text" id="scheduleNameInput" class="form-control">
あ、すべての form 部品に name 属性がされていないです！
これではリクエストに何も入らないので、PHP が値を受け取れません！

2022-06-19 01:41 UTC, Takuma-Ikeda requested changes

2022-06-19 01:41 UTC, Takuma-Ikeda commented on schedule/edit.html
> +          <input type="time" id="scheduleTimeInput" class="form-control-times" value="12:00">
id の使い方を間違ってますね。id の値は重複がない「ユニーク」なものであるべきです。
`scheduleTimeInput` が 3 つありますねので不適切となります。
もし id を付けたいなら開始時刻・終了時刻を意味する英単語でいいと思います。
共通の style をあてたいだけなら `scheduleTimeInput` は class に設定しましょう。

2022-06-19 01:56 UTC, Takuma-Ikeda commented on schedule/edit.html
> +          <input type="time" id="scheduleTimeInput" class="form-control-times" value="12:00">
ちなみにですが、id や name の接尾語に `Input` は付けなくていいかなと思います。PHP が値を受け取るときは Form タグの input からやってきたことは自明なので、わざわざ Input と書く必要はないかなと。
Laraqvel ではラクに書きたいので `start_date` とか `finish_date` のような値のほうが取り回しやすいし、バリデーション

[BEM](https://www.northdetail.co.jp/blog/1953/) みたいな定番ルールもありますが、

2022-06-19 02:47 UTC, Takuma-Ikeda requested changes

2022-06-19 02:47 UTC, Takuma-Ikeda commented on index.html
> +          <a href="./schedule/detail.html" class="thisday">
遷移先が日付を識別できないので `?date=2022-06-01` などのパラメータをつけておいてください

2022-06-23 04:58 UTC, katakabe commented on index.html
> +          <a href="./schedule/detail.html" class="thisday">
修正いたしました。
お手すきの際にご確認お願いいたします！

2022-06-23 04:58 UTC, katakabe commented on index.html
> +  <title>Calendar</title>
修正いたしました。
お手すきの際にご確認お願いいたします！

2022-06-23 04:59 UTC, katakabe commented on css/style.css
> +
修正いたしました。
お手すきの際にご確認お願いいたします！

2022-06-23 04:59 UTC, katakabe commented on schedule/create.html
> +  (c) EeeeG, Inc.
失礼いたしました…。
resolve 機能については考えを改め、コメントいただいた後に resolve を実施いたします！

2022-06-23 05:00 UTC, katakabe commented on schedule/create.html
> +  <div class="calendar-container">
修正いたしました。
ご査収のほどお願いいたします！

2022-06-23 05:01 UTC, katakabe commented on schedule/create.html
> +    <div class="calender-content">
失礼いたしました、全般見直しを実施しました。。
ご査収のほどお願いいたします！

2022-06-23 05:01 UTC, katakabe commented on schedule/detail.html
> +  <div id="detailLists">
仰る通り、そもそもここの div 不要でした。
修正いたしました。
ご査収のほどお願いいたします！

2022-06-23 05:02 UTC, katakabe commented on schedule/detail.html
> +      <th>タスク</th>
修正いたしました。
ご査収のほどお願いいたします！

2022-06-23 05:02 UTC, katakabe commented on schedule/detail.html
> +      <th>時刻</th>
修正いたしました。
ご査収のほどお願いいたします！

2022-06-23 05:02 UTC, katakabe commented on css/style.css
> +.listInput {
こちら ListInput が不要だったため削除して対応いたしました。

2022-06-23 05:03 UTC, katakabe commented on schedule/edit.html
> +          <input type="text" id="scheduleNameInput" class="form-control" value="A社とミーティング">
> 池田や Fusic は基本的に PHP の変数名・メソッド名はキャメルケース、それ以外のすべてをスネークケースにしています。

上記参考にさせていただいた上で修正いたしました。

2022-06-23 05:03 UTC, katakabe commented on schedule/create.html
> +          <input type="text" id="scheduleNameInput" class="form-control">
修正いたしました。
ご査収のほどお願いいたします！

2022-06-23 05:03 UTC, katakabe commented on schedule/edit.html
> +          <input type="time" id="scheduleTimeInput" class="form-control-times" value="12:00">
失礼いたしました。
こちら修正いたしました。

2022-06-24 00:52 UTC, Takuma-Ikeda requested changes
レビュー追加しました！

2022-06-24 00:52 UTC, Takuma-Ikeda commented on index.html
> +        <td class="sat">2</td>
Slack にも書かせてもらいましたが、他の日付がリンク化されていないのはモックとしておかしいのでご対応よろしくお願いします。
7/1 以外の遷移先のモック画面は不要です。

2022-06-24 00:52 UTC, Takuma-Ikeda commented on css/style.css
> +a:hover {
a:hover ってすべてのリンクに背景色が付いちゃうのであんまりよくないと思います。
特定 class が hover されたときに背景色がつくようにしてください。

2022-06-24 00:52 UTC, Takuma-Ikeda commented on schedule/create.html
> +  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
Slack にも書かせてもらいましたが、全ての画面に YUI の CDN を適用して Bootstrap のデザインを適用していってください。

```html
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
```

2022-06-24 00:52 UTC, Takuma-Ikeda commented on schedule/detail.html
> +      <th></th>
削除・編集ボタンを入れるために空の `<th>` が 2 つ並んでいると思うんですが、
セルを分けてしまうと、互いのボタン間隔をピクセル単位で調整できませんね。
th タグの中身が空っぽだと意図も分かりにくいので `<th>アクション</th>` 1 つでいいと思います。
ボタン間隔はスタイリングしてください。

2022-06-24 00:52 UTC, Takuma-Ikeda commented on css/style.css
> +  color: black;
細かい調整したい場合があると思うので、プロっぽく16 進数のカラーコード使いましょうか。
`#000000` みたいな感じで color 指定してください！

2022-06-24 01:03 UTC, Takuma-Ikeda requested changes

2022-06-24 01:03 UTC, Takuma-Ikeda commented on schedule/detail.html
> +      <th>予定日時</th>
あ、細かいですが「予定日時」だと値には日付も含めないといけないですね！
ただ、7/1 no詳細画面であることが明らかなので「予定時刻」とすればいいと思います。
すべての画面を「予定時刻」に変更おねがいします。

2022-06-24 01:13 UTC, Takuma-Ikeda requested changes

2022-06-24 01:13 UTC, iQeda commented on schedule/edit.html
> +          <input type="text" id="schedule_name" class="form-control"  name="schedule_name" value="A社とミーティング">
Laravel で値を受け取るときですが、たとえば...ScheduleController の store アクションでデータ保存をすることになると思います。
つまり処理する側は「スケジュール」に関する値が飛んでくることはわかっているわけですね。
なので `schedule_name` という値にする必要はなくて `name` だけで十分だと思います。
データベースのカラム名 (attiribute) はできるだけシンプルにしたいので

- name
- detail
- started_at  (Laravel の created_at などに似た命名にする)
- finished_at  (Laravel の created_at などに似た命名にする)

とかでいいと思います！フレームワークを使っていない現場では接頭辞付けないと混乱しがちですが、これぐらいシンプルなフレームワークアプリだといいかなって感じがします。

2022-06-24 01:13 UTC, Takuma-Ikeda commented on schedule/edit.html
> +          <input type="text" id="schedule_name" class="form-control"  name="schedule_name" value="A社とミーティング">
id, name などの見直しをお願いします！

2022-06-24 10:14 UTC, katakabe commented on css/style.css
> +a:hover {
こちら class 付けていない状態となります。
次回 push にて併せて対応します。

2022-06-24 12:02 UTC, Takuma-Ikeda reviewed
@katakabe 
対応した内容をコメントしました！

2022-06-24 12:02 UTC, iQeda commented on css/style.css
>  h1 {
CSS ファイルですが

・HTML タグそのものにスタイルしている箇所 (上のほう)
・class にスタイルしている箇所 (下の方)

それぞれまとめて、コメントで区別しています
全部ぐちゃぐちゃだったので整理している感じです
本来であればもっと整理したいのですが、スタイルの定義場所は探しやすいようにまとめてもらえれば！

2022-06-24 12:02 UTC, iQeda commented on index.html
> +        <thead>
こちらも thead / tbody を追加しています

2022-06-24 12:02 UTC, iQeda commented on index.html
> +      <h1 class="mb-5">2022年7月</h1>
詳細画面では半角スペースなかったので削除しています

2022-06-24 12:02 UTC, iQeda commented on index.html
> +          <tr class="day_of_week">
week (週) じゃなくて day_of_week (曜日) でスタイリングし直しました

2022-06-24 12:02 UTC, iQeda commented on index.html
> +          <tr class="week">
各週の class 名は date (日時) じゃなくて week (週) のほうが適切だと思ったので変更しています
毎週の行ごとに week でラップしています

2022-06-24 12:02 UTC, iQeda commented on index.html
> +              <a href="./schedule/detail.html?date=2022-07-02">
日付リンクの GET パラメータがすべて `07-01` のままだったので、それぞれの日付になおしています

2022-06-24 12:02 UTC, iQeda commented on index.html
> +                <div class="schedule">
schedule は複数行になる可能性があるので div でラップすることにしました

2022-06-24 12:02 UTC, iQeda commented on index.html
> +      <div class="fixed-bottom">
Bootstrap のクラス指定で簡単にフッター固定できるので push を取り除いています
`fixed-bottom` で調べてみてください

2022-06-24 12:02 UTC, iQeda commented on index.html
> +        <footer>&copy; EeeeG, Inc.</footer>
フッター内容をわざわざ p タグで囲む必要ないので削除しています
p は「パラグラフ」(文章) の意味なので不適切ですし、p タグデフォルトの margin-bottom が消えてなくてフッターが崩れていたためです

2022-06-24 12:02 UTC, iQeda commented on schedule/create.html
> +    <div class="container">
全画面に広がりすぎていたため、container で左右に余白をつけるようにしました

2022-06-24 12:02 UTC, iQeda commented on schedule/create.html
> +      <form action="../index.html" method="post">
form の action / method は必須なので忘れないようにしてください
特に action は送信後、どの画面に遷移するのか試験上では大事な情報ですので

2022-06-24 12:02 UTC, iQeda commented on schedule/create.html
> +          <input type="submit" class="btn btn-primary" value="新規作成" />
送信ボタンとなる input は `type="submit"` にすることを忘れないでください

2022-06-24 12:02 UTC, iQeda commented on schedule/create.html
> +          <button
キャンセルボタンは `form` の中で `input` して送信する類のものではないので、
button タグに変更しています。
input にしているとまるでサーバーにリクエスト値を投げている印象がありますので。

2022-06-24 12:02 UTC, iQeda commented on schedule/detail.html
> +      <div class="text-end">
Bootstrap の `text-end` で右寄せにしています
※ text-top というクラス名・スタイリング内容が謎だったので、命名するときは他の人がわかるようにしてもらえればと

2022-06-24 12:02 UTC, iQeda commented on schedule/detail.html
> +        <button
ここも form タグの中ではないので input タグではなく button タグにしています

2022-06-24 12:02 UTC, iQeda commented on schedule/detail.html
> +        >戻る</buton>
こちらの戻るボタンも同様に input タグをやめています

2022-06-24 12:02 UTC, iQeda commented on schedule/detail.html
> +              <button
こちらも form の中ではないので input ではなく button に変更しています

2022-06-24 12:02 UTC, iQeda commented on schedule/detail.html
> +              <button
mini-button いらなかったので削除しています

2022-06-24 12:02 UTC, Takuma-Ikeda commented on css/style.css
> +.button_wrap {
button タグを囲む div のクラス名が `button` っていう名前になっていました。
この名前ではボタンだと勘違いしてしまうので `button-wrap` に変更しています。

2022-06-24 12:02 UTC, Takuma-Ikeda commented on css/style.css
> +  text-align: center;
カレンダーの曜日を中央寄せにしました。

2022-06-24 12:06 UTC, Takuma-Ikeda commented on css/style.css
> -.mb-5 {
bootstrap のクラス名のクラス名とコンフリクトしているので、こういったクラスを独自定義しないよう注意してください。
※ bootstrap が用意しているクラスが崩れてしまう

mb はマージンボトムの略ですね。下に余白をつける便利なものです

2022-06-25 02:11 UTC, Takuma-Ikeda reviewed
追加対応しました
コメント読んだらスタンプください〜

2022-06-25 02:11 UTC, iQeda commented on css/style.css
> +  background: #99FFCC;
背景色が灰色だと、スケジュールの文字色が黒なので見にくかったので緑色にしました。

2022-06-25 02:11 UTC, iQeda commented on css/style.css
> -a:hover {
この書き方だと、他の a タグにも影響を与えてしまいます。
※ カレンダーの前月・来月のリンクにも背景色がついてしまった
`.day:hover` に変更しました。

2022-06-25 02:11 UTC, iQeda commented on css/style.css
> -table td a:hover{
カレンダー日付の hover 背景色で青色・灰色の重複があったので、灰色のこちらを削除しています。

2022-06-25 02:11 UTC, iQeda commented on css/style.css
> -  margin: 50px 0 50px 100px;
マージンが多いので 32 px にしました。
※ 基本的に px は 8 の倍数にしてください

2022-06-25 02:11 UTC, Takuma-Ikeda commented on index.html
> +      <div class="row">
Bootstrap の row と col の機能を使っています。
本当はすべての画面に適用して、モバイル最適化されたレスポンシブ対応したいところですが、いまから対応すると時間がかかるのでやめておきましょう。

Bootstrap でレスポンシブ対応してほしいと依頼されたら container / row / col を併せて使ってほしいです。

2022-06-25 02:11 UTC, Takuma-Ikeda commented on index.html
> +            <th>日</th>
曜日ヘッダーに day クラスはおかしいので削除

2022-06-25 02:11 UTC, Takuma-Ikeda commented on index.html
> +            <td></td>
day:hover で背景色をつけるように修正したので、
日付のないセルは day クラスを外すようにしました

2022-06-25 02:11 UTC, Takuma-Ikeda commented on index.html
>                    <p>他2件</p>
他2件と書いてるにも関わらず、他2件が詳細画面にありませんでした。
また、カレンダーの日付セル内にもっとスケジュール入りそうだったので最大3件の表示にしています。

2022-06-25 02:11 UTC, Takuma-Ikeda commented on index.html
>                    <p>他2件</p>
元々のスケジュールはそもそもセル枠内で見きれてないですね。
三点リーダ対応するのは見切れる場合だけです。

またモックとして、すべてのダミーデータを「...」三点リーダにしてしまうと、何文字以上で三点リーダ対応するのかわからないですね。
今回は 10 文字以上のスケジュールに対してのみ対応することにし、三点リーダ対応しているもの、していないものを織り交ぜるようにしました。

2022-06-25 02:11 UTC, Takuma-Ikeda commented on schedule/create.html
> +        <div class="form-group mb-3">
こちら指摘の対応漏れですね。フォーム部品の上下間隔が詰まったままでした。
Bootstrap の `mb-3` でマージンボトムを適用して見やすくしました。

2022-06-25 02:11 UTC, Takuma-Ikeda commented on schedule/detail.html
> +              <button type="button" class="btn btn-danger" onclick="deleteAlert('A社とミーティング')">
削除ボタン押下で確認アラートが出るようにしました。

2022-06-25 02:11 UTC, Takuma-Ikeda commented on schedule/detail.html
> +              <button type="button" class="btn btn-danger" onclick="deleteAlert('コーディング試験')">
カレンダーで「他2件」と書かれていましたが、詳細画面にその「他2件」のスケジュールがなかったので追加しています

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> +body {
`.container` の中でフォントファミリーを変更していました。
こちらは Bootstrap のクラスなので、勝手に変更しないほうがよいです。
body の中身のフォントを統一できていればいいので、そのように変更しました。

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> +  width: 128px;
カレンダーのセルが大きかったので小さくしています。
※ こちらも 8 の倍数です

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> +table td a {
半角スペースが必要です。
prettier の自動整形が効いてない場合は  VS Code で `Format Document` コマンドを実行してみてください。

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> +  padding: 8px 0;
8 の倍数対応

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> -.mini-button {
使ってないので削除

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> +.sun, .holiday {
同じスタイルを適用しているなら `,` 区切りでまとめてもらえると把握しやすいです

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> -a {
すべての a タグが 100% width になっていたので削除
※ リンクの文字列以上に、見えないクリック判定ができていたため

そもそもこちらのスタイルは `.day a` だけが対象なので、そちらに移動

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> +.day {
CSS ファイル内で `.day` 周りの定義は同じ箇所にかためました。
このように似た定義はかためてもらえると助かります。

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> -.button {
他にも .button が生きていたので削除

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> -.push {
Bootstrap を使ってフッター固定するようにしたので削除

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> -  margin-top: 10px;
ちょっとマージン付けたいだけなら、HTML タグに直接 `mt-2` などを付けましょうか。
こちらは Bootstrap のマージントップを付与するクラスとなります。

ただ今回は label と input の間を調整したいだけなので `mt-2` ではなく、マージンボトムの `mb-2` にしています。
※ ラベルの下に余白をつけた

2022-06-26 01:59 UTC, Takuma-Ikeda commented on schedule/create.html
> -          <label for="schedule_datail">予定詳細</label>
`schedule_detail` のままになっていました。
`detail` に修正しています。
※ edit のほうも同様です

2022-06-26 01:59 UTC, Takuma-Ikeda commented on css/style.css
> -.table-striped {
こちらも Bootstrap のクラスなのでスタイル変更しないほうがよいです。
マージントップがほしいだけなので HTML タグに直接 `mt-4` をつけています。

2022-06-26 03:08 UTC, Takuma-Ikeda commented on schedule/create.html
> +          <label class="mb-2" for="datail">詳細</label>
画面によって、予定のことを「スケジュール」と書いていたり、「予定」と書いていたりで一貫性がないですね。
今後の方針として「スケジュール」という名称を使うことにします。
ですが、ここではスケジュールを作成しているのにわざわざ「スケジュール詳細」という長いラベルにする必要もないので「詳細」としました。

2022-06-26 03:10 UTC, Takuma-Ikeda commented on schedule/create.html
> +          <label class="mb-2" for="date">日付</label>
予定という和名を使いたくないので、予定日をやめました。

2022-06-26 04:07 UTC, iQeda commented on css/style.css
> -table td {
いろんなページで table を使っており、width と height の影響を受けていたので class 指定に変更しています

2022-06-26 04:07 UTC, iQeda commented on css/style.css
> +  color: #ffffff;
3 桁の 16 進数で表記する場合もありますが、他と合わせるため `#fff` じゃなくて `#ffffff` にしました。
たぶん業界デファクトは 6 桁のほうです。

2022-06-26 04:07 UTC, Takuma-Ikeda commented on schedule/index.html
>  <html lang="ja">
ファイル名を detail から index に変更しています。
フレームワークでは CaldendarController と ScheduleController の 2 つになると思っており、
ScheduleController の index アクションこそが今の「スケジュール詳細画面」になるはずだからです

ただ「スケジュール詳細画面」のままだとニュアンスが show アクションっぽいので、
`schedule/index.html` は「スケジュール一覧画面」の役割に変更し、
`schedule/show.html` は「スケジュール詳細画面」として個別スケジュールの詳細確認する役割をもたせました。

2022-06-26 04:07 UTC, Takuma-Ikeda commented on schedule/show.html
> +              <td>先方から Zoom URL がメールで届くので確認すること</td>
こちらで詳細を表示するようにしています

2022-06-26 04:07 UTC, Takuma-Ikeda commented on schedule/index.html
> -            <th>詳細</th>
index では詳細をなくし、show のほうで詳細確認する仕様にしました

2022-06-26 23:09 UTC, Takuma-Ikeda commented on css/style.css
> +a:hover {
こちら対応しました！

2022-06-26 23:10 UTC, Takuma-Ikeda commented on schedule/create.html
> +  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
こちら対応ありがとうございます！

2022-06-29 10:09 UTC, iQeda requested changes

2022-06-29 10:09 UTC, Takuma-Ikeda commented on css/style.css
> +  margin-bottom: 50px;
@katakabe 
あ、基本的に 8 の倍数を基準にしたのでお願いします！
48px か 56px でいけませんか？

2022-07-01 10:14 UTC, Takuma-Ikeda commented
@katakabe 
LGTM です！マージをよろしくお願いします！
コミットが汚れているので main ブランチの rebase も併せてよろしくお願いします！

2022-07-11 06:31 UTC, merged